const CONFIG = {
  OPENROUTER_API_KEY: "YOUR_OPENROUTER_API_KEY",
  UMAMI_WEBSITE_ID:   "",
  UMAMI_PUBLIC_KEY:   "",
  GOATCOUNTER_CODE:   "",
  GITHUB_REPO:        "YOUR_GITHUB_USERNAME/Human-OS"
};
window.CONFIG = CONFIG;
